FROM python:3.11-slim

# Herramientas necesarias
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg \
        curl \
        git \
        unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Instalar Deno
RUN curl -fsSL https://deno.land/install.sh | sh \
    && mv /root/.deno/bin/deno /usr/local/bin/deno

# Directorio principal
WORKDIR /app

# Dependencias Python
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir -U bgutil-ytdlp-pot-provider

# Descargar BgUtils
RUN git clone \
    --single-branch \
    --branch 2.0.0 \
    https://github.com/Brainicism/bgutil-ytdlp-pot-provider.git \
    /app/bgutil-ytdlp-pot-provider

# Instalar dependencias de BgUtils
WORKDIR /app/bgutil-ytdlp-pot-provider/server

RUN deno install --allow-scripts=npm:canvas --frozen

# Volver a la aplicación
WORKDIR /app

COPY main.py .

RUN mkdir -p temp_downloads

EXPOSE 10000

# Iniciar BgUtils y FastAPI
CMD ["sh", "-c", "cd /app/bgutil-ytdlp-pot-provider/server && deno run --allow-env --allow-net --allow-ffi=./node_modules --allow-read=. src/main.ts --host 127.0.0.1 --port 4416 & uvicorn main:app --host 0.0.0.0 --port ${PORT:-10000}"]
